StartupsPoleEmploi/zen

- back/migrations/20180502153346-create-declaration.js
- back/models/declaration.js
- back/routes/employers.js
- front/src/App.js
- front/src/pages/actu/Employers.js
Also adds a Stepper to let the user know the states and return to previous ones
> Redirections when loading the app

- front/src/pages/actu/Files.js
Follow up broken https://github.com/StartupsPoleEmploi/actualisation/pull/17
> fix number of documents to provide calculation

- back/routes/declarations.js
- back/routes/employers.js
- back/routes/login.js
Weren't handled in a lot of cases.
> Catch server promise errors

- back/app.js
- back/migrations/20180615105013_activity-logs.js
- back/migrations/20180615144606_administrators.js
- back/models/ActivityLog.js
- back/models/Administrators.js
- back/package-lock.json
- back/package.json
- back/routes/admin.js
- back/routes/declarations.js
- back/routes/employers.js
> User activity log

- back/app.js
- back/lib/activeMonthMiddleware.js
- back/migrations/20180619102708_declaration_months.js
- back/models/Declaration.js
- back/models/DeclarationMonth.js
- back/models/__tests__/Declaration.js
- back/routes/__tests__/declarations.js
- back/routes/__tests__/employers.js
- back/routes/declarationMonths.js
- back/routes/declarations.js
- back/routes/employers.js
- back/tests/globalSetup.js
- front/src/App.js
- front/src/components/Actu/EmployerQuestion.js
- front/src/components/Generic/DatePicker.js
- front/src/index.js
- front/src/pages/actu/Actu.js
- front/src/pages/actu/Employers.js
- front/src/pages/actu/Files.js
Previously, May 2018 was hard coded everywhere
> handle multiple months

- back/routes/login.js
- front/src/App.js
- front/src/pages/home/Home.js
Previously it directly showed a backend error.
This is when the user cancels his login.
> better login error

- front/src/components/Actu/AdditionalDocumentUpload.js
- front/src/components/Actu/DeclarationQuestion.js
- front/src/components/Actu/EmployerDocumentUpload.js
- front/src/components/Actu/EmployerQuestion.js
- front/src/pages/Layout.js
- front/src/pages/actu/Actu.js
- front/src/pages/actu/Employers.js
- front/src/pages/actu/Files.js
> Layout improvements

- back/lib/serviceUpMiddleware.js
- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/__stories__/AdditionalDocumentUpload.js
- front/src/components/Actu/__stories__/EmployerDocumentUpload.js
- front/src/components/Actu/__stories__/EmployerQuestion.js
- front/src/components/Generic/__stories__/EuroInput.js
- front/src/components/Generic/__stories__/HourInput.js
- package.json
Based on #79 which should be merged first
> Fix tests and run them on git push

- back/lib/pe-api/__tests__/__snapshots__/declaration.js.snap
- back/lib/pe-api/__tests__/__snapshots__/documents.js.snap
- back/lib/pe-api/__tests__/declaration.js
- back/lib/pe-api/__tests__/documents.js
- back/lib/pe-api/declaration.js
- back/lib/pe-api/documents.js
- back/models/Declaration.js
- front/.eslintrc.js
- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/AdditionalDocumentUpload.js
- front/src/components/Actu/DeclarationQuestion.js
- front/src/components/Actu/__stories__/DeclarationQuestion.js
- front/src/pages/actu/Actu.js
- front/src/pages/actu/Files.js
Handle multiple internships and sick leaves, for declarations and documents.
> Handle multiple internships and sick leaves

- back/routes/declarations.js
- back/routes/employers.js
Stop using upsertGraph on documents and do more economic operations
This should also prevent a bugs we did not understand where another declaration could get created
> back: refactor documents uploads

- back/routes/declarations.js
- back/routes/employers.js
plus correctly return employer / declaration after request
> back fix: correctly save declaration/employerId with docs

- back/lib/pe-api/__tests__/__snapshots__/declaration.js.snap
- back/lib/pe-api/__tests__/declaration.js
- back/lib/pe-api/declaration.js
- package.json
Old limit 450 hours can't be used anymore
> back fix: change PE max declarable work hours to 420

- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/UserJobCheck.js
review @codeheroics 
Note: il faudra qu'on évoque le système de `snap` pour tes tests
> Update entrepreneur warning with an 'I get it' button

- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/UserJobCheck.js
> Update entrepreneur message

- back/package.json
- back/yarn.lock
Using v1.6.7 generated an error with declaration.().upsertGraph
which needs to be investigated
> back fix: revert and pin objection to 1.4

- back/routes/admin.js
This loads an optional json file which contains the mail of the users to exclude.
> back admin: prevent some users from being authorized

- front/src/components/Actu/WorkSummary.js
- front/src/pages/actu/Employers.js
> Redesign work summary

- back/lib/pe-api/__tests__/documents.js
- back/lib/pe-api/documents.js
were mistakenly sent as salary sheets
> back: fix employers certificate transmission

- front/src/components/Actu/DeclarationDialogs/DeclarationSummaryDialog.js
Colors tweaks (switching to style="secondary", which is the same as primary but will change while https://github.com/StartupsPoleEmploi/zen/pull/160 is merged), wording fixes, styles cleanup
> Tweak declaration summary dialog

- back/admin.js
- back/app.js
- back/knexfile.js
- back/lib/db.js
- back/mailing-agent.js
- back/tests/getKnexTestInstance.js
- back/tests/globalSetup.js
- back/tests/globalTeardown.js
- back/tests/setup.js
Problème de gestion des nombres décimaux de postgresql causait l'apparition de NaN dans le PDF.
Corrigé en setuppant mieux la db partout dans l'app
> Fix pg float operations

- front/src/components/Actu/DeclarationDialogs/DeclarationDialogsHandler.js
- front/src/components/Actu/DeclarationDialogs/DeclarationSummaryDialog.js
- front/src/pages/actu/Actu.js
@AlexandreCantin https://github.com/StartupsPoleEmploi/zen/pull/149 a cassé le formulaire de déclaration sur la première page =/
> Fix declaration form

- front/src/pages/actu/Files.js
Were never correctly displayed if errors when sending files
> front: fix Files submit error display

- back/routes/admin.js
- front-admin/src/pages/Users.js
- front-admin/src/pages/UsersFilter.js
- front-admin/src/pages/UsersList.js
Objectif, filtrer dans une liste de mails et en retirer les e-mails inscrits
> Page admin de filtre d'emails 

- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/EmployerQuestion.js
- front/src/components/Generic/YesNoRadioGroup.js
- front/src/pages/actu/Actu.js
- front/src/pages/actu/Files.js
- front/src/pages/actu/Thanks.js
- front/src/pages/home/Home.js
~Based on commits of #181, should be reviewed after it is merged.~
> Styling tweaks for Actu and Employers pages

- front/src/App.js
- front/src/components/Actu/DocumentUpload.js
- front/src/components/Actu/WorkSummary.js
- front/src/components/Generic/AppTitle.js
- front/src/components/Generic/MainActionButton.js
- front/src/components/Generic/Rectangle.js
- front/src/components/Generic/TooltipOnFocus.js
- front/src/constants/index.js
- front/src/pages/Layout.js
- front/src/pages/actu/Actu.js
- front/src/pages/actu/Employers.js
- front/src/pages/actu/Files.js
- front/src/pages/home/Home.js
New nav for desktop and mobile
> front: new navigation

- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/DocumentUpload.js
- front/src/components/Generic/TooltipOnFocus.js
- front/src/pages/actu/Files.js
Also tweaks a bit the display to have the old documents interface feat correctly with the new navigation
> Show all olds documents

- back/migrations/20190613151111_add_cleanedup_column.js
@AlexandreCantin Le rollback ne fonctionnait pas correctement, attention à bien tester migration > rollback > nouvelle migration
> back db: fix isCleanedUp migration rollback

- package.json
Permet de jouer les migrations et rollback via `yarn run`
> dev:easier knex migrate/rollback with npm commands

- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/DeclarationQuestion.js
- front/src/components/Actu/__stories__/DeclarationQuestion.js
- front/src/pages/actu/Actu.js
Plus some refactoring, unbreakable spaces added
> front: vertical Layout for DeclarationQuestions on small screens

- back/routes/admin.js
Switch to french to avoid confusion due to the fix
> front: rename users extract files

- front/src/pages/actu/Files.js
> front: fix Files page: some documents couldn't be skipped

- front/src/pages/actu/Files.js
> front: Files page - fix missing files number calculation

- cypress.json
- cypress/integration/Actu_spec.js
- cypress/pages/Actu.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- package.json
* Wait for node and front containers to be correctly started before running tests
* Fix Actu tests
> Fix e2e tests setup

- back/yarn.lock
- front/yarn.lock
> front & back: add updated yarn.lock missing from #192

- back/.eslintrc.js
- back/lib/cleanOldFiles.js
- back/lib/declaration.js
- back/lib/files.js
- back/lib/mailings/sendDocumentReminders.js
- back/lib/pdf-utils.js
- back/routes/declarations.js
- back/routes/employers.js
- back/routes/login.js
- cypress/.eslintrc.js
- front-admin/.eslintrc.js
- front-admin/src/pages/UsersEmails.js
- front-admin/src/pages/UsersFilter.js
- front-admin/src/pages/UsersList.js
- front/.eslintrc.js
- front/src/components/Actu/DeclarationDialogs/ConsistencyErrorsDialog.js
- front/src/components/Actu/DeclarationDialogs/ErrorsDialog.js
- front/src/components/Actu/DeclarationDialogs/LoadingDialog.js
- front/src/components/Actu/DocumentUpload.js
- front/src/components/Generic/documents/DocumentDialog.js
- front/src/pages/actu/Files.js
- front/tests/setup.js
- package.json
`eslint --fix` avec deux nouvelles règles
> chore: actiate eslint rules arrow-body-style & curly

- back/lib/pe-api/__tests__/declaration.js
- back/lib/pe-api/declaration.js
- back/routes/declarations.js
- back/routes/employers.js
Automatically try again after pe api sends back HTTP 200 with "not saved" error. (plus some refactor)
> Handle "declaration not saved" error

- cypress/integration/Files_spec.js
- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/DocumentUpload.js
- front/src/components/Actu/__stories__/DocumentUpload.js
- front/src/components/Generic/documents/DocumentDialog.js
- front/src/pages/Layout.js
- front/src/pages/actu/Files.js
Redesign after intermediary version https://github.com/StartupsPoleEmploi/zen/pull/238
> Files page redesign

- back/jobs/utilities-agent.js
- back/lib/exportUserList.js
Export seulement des utilisateurs non autorisés :)
> back: export only unauthorized users

- back/lib/pdf-utils.js
- back/lib/upload.js
- back/routes/declarations.js
- back/routes/employers.js
- front/src/components/Generic/documents/DocumentDialog.js
- front/src/redux/actions/declarations.js
Empêche d'uploader des PDF invalides
> Feature/453 dev je veux identifier les documents pdf qui nen sont pas fichiers html ou autre poussés par erreur

- back/routes/login.js
To see more:
- https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/utiliser-les-api/authorization-code-flow.html
- https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/utiliser-les-api/authorization-code-flow/avec-authentification-etape-1
> back: add silver and  scopes when getting token

- cypress/integration/Employer_spec.js
- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Generic/EuroInput.js
> front: improve suffix label for EuroInput

- front/src/__snapshots__/stories.test.js.snap
- front/src/pages/home/Home.js
> front: update homepage text

- front/public/index.css
- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/DocumentUpload.js
- front/src/components/Actu/EmployerQuestion.js
- front/src/components/Generic/TooltipOnFocus.js
- front/src/components/Generic/YesNoRadioGroup.js
Correction sur les tooltips :smile:
> front: fix tooltip design

- back/migrations/20190613151111_add_cleanedup_column.js
- back/migrations/20190823094646_add_original_name_column.js
- back/package.json
- back/yarn.lock
- front/package.json
- front/yarn.lock
Il reste encore des paquets avec des failles de vulnérabilités connues
> security: update packages

- front/src/components/Generic/MainActionButton.js
- front/src/components/ZnLayout/ZnNavLogin.js
- front/src/pages/actu/Actu.js
- front/src/pages/actu/Employers.js
- front/src/pages/actu/Files.js
> front: design improvements

- front/src/components/Generic/actu/DeclarationClosed.js
- front/src/components/Generic/actu/DeclarationFinished.js
- front/src/components/Generic/actu/DeclarationOnGoing.js
- front/src/pages/dashboard/Dashboard.js
Utilisation d'une constante partagée pour la couleur #1e2c59 :smiley:
> front: use darkBlue instead of duplicate color

- back/lib/admin/metrics.js
- back/routes/admin.js
- front-admin/src/containers/Dashboard/component/metrics/Metrics.js
- front-admin/src/containers/Dashboard/component/metrics/MetricsForm.js
- front-admin/src/containers/Dashboard/component/metrics/metrics.css
- front-admin/src/containers/Dashboard/component/repartition/RepartitionAgency.js
- front-admin/src/containers/Dashboard/component/repartition/RepartitionForm.js
- front-admin/src/containers/Dashboard/component/retention/RetentionResults.js
- front/src/components/Generic/DeveloperDialog/DialogActualisation.js
- front/src/pages/actu/Files.js
- front/src/pages/history/MissingCell.js
New retention + downloable graph + accumulate datas
> admin: graph improvments

- front/src/__snapshots__/stories.test.js.snap
- front/src/components/Actu/EmployerQuestion/EmployerQuestionSalaryModal.js
> fix(): ajoute &nbsp; dans popin covid

- back/migrations/20210118103748_declaration-months-2021.js
- front/src/components/Generic/DialogHelp.js
- front/src/pages/other/Cgu.js
Passage dev fix FAQ grisé sur master
> Passage dev fix FAQ grisé sur master

- docker-compose.yml
> (fix) mise à jour wordpress

- docker-compose.yml
mise a jour de la confi pour backup prod
> (fix) mise en place backup de prod
