StartupsPoleEmploi/zen

back/routes/login.js

All of our users are able to send declaration-related documents

back: Remove check of accessible contexts

---

front/src/pages/actu/Employers.js

Harmless because it caused logged error, but had the same effect as an empty return, which was what it was supposed to do

front: fix harmless cDU crash on Employers page

---

back/lib/mailings/sendDeclarationConfirmationEmails.js

Mistakenly showed maternity leave when sick leaves were declared

back: fix declaration confirmation document generation

---

front/src/App.js

This avoids an error which appeared because user was in the app's state even though the token had expired

front fix: detect earlier invalid user tokens for login redirection

---

front/src/pages/actu/Actu.js

wrong conditions were used to check retirement and invalidity dates

front: fix actu form validation

---

front/package.json

* add missing regenerator-runtime for prod builds
* remove warning by setting babel-preset-env option corejs

fix front dependencies

---

front/src/__snapshots__/stories.test.js.snap
front/src/pages/home/Home.js

fixes media queries triggers on iphone / ipad
references:
https://zellwk.com/blog/media-query-units/
https://adamwathan.me/dont-use-em-for-media-queries/

front: use px instead of rem in media queries

---

back/lib/mailings/mailjet.js

The emails were sent in bulk with all users (about 50 at a time) visible in the To field
@AlexandreCantin Le truc était donc pas d'utiliser le champ BCC mais de faire un array de messages avec destinataires en fait, et hop ça fonctionne comme voulu

back: fix sending bulk validation emails

---

back/config/default.js
back/lib/mailings/mailjet.js

@AlexandreCantin Comme on en parlait et suite au fiasco de ce matin, manière plus facile d'overrider les emails envoyés hors prod : Ajouter un `testEmail` à la config node, et si le mode Sandbox est désactivé, tous les mails partiront vers cette adresses

back: add the ability to have a test email specified in the configuration

---

cypress/integration/Files_spec.js
cypress/pages/Files.js
front/src/__snapshots__/stories.test.js.snap
front/src/components/Actu/DocumentUpload.js
front/src/components/Generic/CustomDialog.js
front/src/components/Generic/PDFViewer.js
front/src/components/Generic/documents/DocumentDialog.js
front/src/pages/actu/Files.js

Code retravaillant les changements mergés dans https://github.com/StartupsPoleEmploi/zen/pull/192
Divers points adaptés / corrigés, mais en vrac : 
* Simplification du code, notamment des styles (cf diff, 100 lignes de moins après ceci). Comprend notamment :
* Usage du composant `CustomDialog` utilisés pour le reste des modals (un peu améliorés pour l'occasion)
* Suppression au maximum de spécificités nécessitant des media-queries
* Suppression de l'utilisation d'anti-patterns (`.then` et `.catch` suivant des requêtes HTTP dans composants parents). La modification (l'utilisation de `componentDidUpdate` en réaction à des modifications de props) n'est pas non plus idéale, mais est moins dangereuse, en attendant meilleure réécriture.
* Meilleure adaptation des documents aux modals …

front: Ajustements modal PDF

---

front/package.json
front/src/__snapshots__/stories.test.js.snap
front/src/components/Generic/documents/DocumentDialog.js

Passage du PDF Viewer en lazy load.
Effet sur le front : 
`npm run build` après https://github.com/StartupsPoleEmploi/zen/pull/192
```
File sizes after gzip:
553.99 KB (+331.94 KB)  build/static/js/2.f955dbb6.chunk.js
40.97 KB (+4.16 KB)     build/static/js/main.cb52cfab.chunk.js
764 B                   build/static/js/runtime~main.42ac5946.js
```
Après ceci : 
```
File sizes after gzip:
323.05 KB               build/static/js/3.2db5feda.chunk.js
230.85 KB (-323.14 KB)  build/static/js/2.f5c59ab5.chunk.js
39.57 KB (-1.4 KB)      build/static/js/main.adf8f9db.chunk.js
1.46 KB                 build/static/js/4.15836f91.chunk.js
1.14 KB (+405 B)        build/static/js/runtime~main.ba226b5f.js
```
Faudra faire un passage sur les dépendances parce que c'est toujours lourd, mais au moins le …

front: lazyload PDFViewer to avoid big dependency dl everytime

---

back/routes/login.js

* handle no answer from pe actualisation api
* handle no answer from pe coordinates api

back: make login more resilient

---

back/routes/declarations.js
back/routes/employers.js

Calculer `originalFileName` dans le cas où un document devait être skippé n'a pas de sense et crashait le back.

back: prevent crash when trying to skip files

---

back/migrations/20190925155246_set-all-finished-until-june.js

Possibilité également : ajouter une ligne de `employer_documents` vide pour chaque employeur qui n'a pas eu de document associé. Permettrait d'éviter de dépendre à jamais du champ `isFinished` pour l'affichage ou non de documents passés (cf maquettes futures page docs)

back: add migration script to mark all declarations,  docs until june 2019 as done

---

back/lib/refreshAccessTokenMiddleware.js

Lors des tests, la session n'a pas de `user.tokenExpirationDate`...

back: do not attempt token refesrh if no user or no tokenExpirationDate

---

back/.gitignore
back/ecosystem.config.js
back/jobs/utilities-agent.js
back/lib/exportUserList.js
back/routes/admin.js
docker-compose.prod.yml
docker-compose.yml

Cette PR a pour but d'exporter la liste de nos utilisateurs automatiquement vers le serveur du Datalake. Quelques notes techniques permettant de mieux comprendre la PR :
- Un dossier partagé avec le datalake est présent sur notre serveur de prod (`/mnt/datalake/vers_datalake`). Régis l'avait mis en place jadis (et pour les toutes les start-ups)
- Le nom du fichier doit absolument être fixe (le datalake ne gère les noms variables)
La seconde étape consistera à récupérer et traiter le fichier-réponse du datalake mais ça se fera plus tard :smile:

Automatic user export list as CSV

---

back/app.js
front/src/index.js

Necessary because PE's QA env is… kinda… down all the time =_=

chore: allow developer dialog in QA env

---

back/lib/declaration.js

The update + problems with UTC caused the declaration_months dates to be moved by 1 day backwards on every update

back: fix: declaration_months was updated by mistake

---

cypress/integration/Actu_spec.js
cypress/pages/Actu.js

Un test e2e échoue assez régulièrement et c'est agaçant, ce changement est une tentative de l'éviter, mais forcément faut faire tourner les e2e 5-6 fois pour s'assurer que ça fonctionne bien, donc c'est en cours :)

front: fix randomly failing e2e tests

---

back/lib/exportUserList.js
docker-compose.prod.yml

Pour que le dossier "/mnt/datalake" (étant un dossier réseau) puisse fonctionner correctement avec le système de volume de Docker, on doit impérativement conserver lié les volumes en conservation le même chemin... et donc faire : `- '/mnt/datalakepe/:/mnt/datalakepe/'`
Il faudra toutefois être vigilant lors de la MEP pour vérifier que tout est ok !

back: export directly in /mnt/datalakepe

---

back/jobs/utilities-agent.js

There is an hour diff between container time and server time, so we need to add an extra hour in your CRON

back: start import datalake one hour later

---

back/lib/mailings/sendDeclarationConfirmationEmails.js

Dans le cas du mail transactionnel, il manquait les infos liés à la candidature.
Du coup, le code : 
```
specialSituations: declaration.infos
.filter((info) => !['jobSearch'].includes(info.type))
...
```
Renvoie : `error: There was an error while sending confirmation email for declaration 24782: TypeError: Cannot read property 'filter' of undefined`

mail: add infos in declaration queries

---

back/routes/developer.js

Le logiciel d'audits de sécurité n'accepte que des URLs fixes et ne peut donc pas se connecter par lui-même...
Du coup, dans les environnements de développement, on permet de se connecter avec un id avec un paramètre dans l'URL

secu: can login as user by id (dev only !)

---

front/src/components/Generic/AppTitle.js

Fix this error => "Warning: React does not recognize the `zenColor` prop on a DOM element "

front: fix zenColor warning
